"""
MediSense AI v3 — Synonym Dictionary
All keys lowercase. Values must exist in model's symptoms_list.
Used by NLPExtractor for strict, non-fuzzy symptom extraction.
"""

SYNONYMS: dict[str, str] = {
    # ── Fever ─────────────────────────────────────────────────────────────────
    "fever":                "high_fever",
    "high fever":           "high_fever",
    "temperature":          "high_fever",
    "feeling hot":          "high_fever",
    "feel hot":             "high_fever",
    "feeling very hot":     "high_fever",
    "feel very hot":        "high_fever",
    "running a fever":      "high_fever",
    "body is hot":          "high_fever",
    "very hot":             "high_fever",
    "mild fever":           "mild_fever",
    "low grade fever":      "mild_fever",
    "slight fever":         "mild_fever",
    "low fever":            "mild_fever",

    # ── Pain ──────────────────────────────────────────────────────────────────
    "stomach pain":         "stomach_pain",
    "stomach ache":         "stomach_pain",
    "tummy pain":           "stomach_pain",
    "tummy ache":           "stomach_pain",
    "pain in stomach":      "stomach_pain",
    "belly pain":           "belly_pain",
    "belly ache":           "belly_pain",
    "abdominal pain":       "abdominal_pain",
    "abdominal ache":       "abdominal_pain",
    "pain in abdomen":      "abdominal_pain",
    "chest pain":           "chest_pain",
    "chest tightness":      "chest_pain",
    "chest pressure":       "chest_pain",
    "pain in chest":        "chest_pain",
    "tight chest":          "chest_pain",
    "back pain":            "back_pain",
    "lower back pain":      "back_pain",
    "pain in back":         "back_pain",
    "neck pain":            "neck_pain",
    "pain in neck":         "neck_pain",
    "knee pain":            "knee_pain",
    "pain in knee":         "knee_pain",
    "hip pain":             "hip_joint_pain",
    "hip joint pain":       "hip_joint_pain",
    "joint pain":           "joint_pain",
    "joint ache":           "joint_pain",
    "pain in joints":       "joint_pain",
    "body pain":            "muscle_pain",
    "body ache":            "muscle_pain",
    "muscle pain":          "muscle_pain",
    "muscle ache":          "muscle_pain",
    "muscular pain":        "muscle_pain",
    "sore muscles":         "muscle_pain",
    "aching all over":      "muscle_pain",
    "headache":             "headache",
    "head pain":            "headache",
    "pain in head":         "headache",
    "pain behind eyes":     "pain_behind_the_eyes",
    "eye pain":             "pain_behind_the_eyes",
    "anal pain":            "pain_in_anal_region",

    # ── Skin ──────────────────────────────────────────────────────────────────
    "rash":                 "skin_rash",
    "skin rash":            "skin_rash",
    "rashes":               "skin_rash",
    "itching":              "itching",
    "itchy":                "itching",
    "itchy skin":           "itching",
    "skin itch":            "itching",
    "itch":                 "itching",
    "redness":              "skin_rash",
    "red spots":            "red_spots_over_body",
    "spots on body":        "red_spots_over_body",
    "blisters":             "blister",
    "blister":              "blister",
    "pimples":              "pus_filled_pimples",
    "acne":                 "blackheads",
    "blackheads":           "blackheads",
    "skin peeling":         "skin_peeling",
    "peeling skin":         "skin_peeling",
    "silver patches":       "silver_like_dusting",
    "skin patches":         "dischromic_patches",
    "yellow skin":          "yellowish_skin",
    "yellowish skin":       "yellowish_skin",
    "jaundice":             "yellowish_skin",
    "yellow eyes":          "yellowing_of_eyes",

    # ── Respiratory ───────────────────────────────────────────────────────────
    "cough":                "cough",
    "dry cough":            "cough",
    "wet cough":            "cough",
    "coughing":             "cough",
    "shortness of breath":  "breathlessness",
    "short of breath":      "breathlessness",
    "breathing difficulty": "breathlessness",
    "difficulty breathing": "breathlessness",
    "can't breathe":        "breathlessness",
    "hard to breathe":      "breathlessness",
    "breathless":           "breathlessness",
    "wheezing":             "breathlessness",
    "sneezing":             "continuous_sneezing",
    "continuous sneezing":  "continuous_sneezing",
    "runny nose":           "runny_nose",
    "nose running":         "runny_nose",
    "stuffy nose":          "congestion",
    "blocked nose":         "congestion",
    "nasal congestion":     "congestion",
    "nose block":           "congestion",
    "phlegm":               "phlegm",
    "mucus":                "phlegm",
    "sputum":               "phlegm",
    "blood in sputum":      "blood_in_sputum",
    "coughing blood":       "blood_in_sputum",
    "throat irritation":    "throat_irritation",
    "sore throat":          "throat_irritation",
    "throat pain":          "throat_irritation",
    "sinus pressure":       "sinus_pressure",
    "sinus":                "sinus_pressure",

    # ── Digestive ─────────────────────────────────────────────────────────────
    "nausea":               "nausea",
    "nauseous":             "nausea",
    "feeling nauseous":     "nausea",
    "feel nauseous":        "nausea",
    "queasy":               "nausea",
    "vomiting":             "vomiting",
    "vomit":                "vomiting",
    "throwing up":          "vomiting",
    "puking":               "vomiting",
    "diarrhea":             "diarrhoea",
    "diarrhoea":            "diarrhoea",
    "loose stools":         "diarrhoea",
    "loose motion":         "diarrhoea",
    "loose motions":        "diarrhoea",
    "runny stool":          "diarrhoea",
    "constipation":         "constipation",
    "cant poop":            "constipation",
    "indigestion":          "indigestion",
    "acidity":              "acidity",
    "acid reflux":          "acidity",
    "heartburn":            "acidity",
    "gas":                  "passage_of_gases",
    "bloating":             "passage_of_gases",
    "flatulence":           "passage_of_gases",
    "loss of appetite":     "loss_of_appetite",
    "no appetite":          "loss_of_appetite",
    "not hungry":           "loss_of_appetite",
    "cant eat":             "loss_of_appetite",
    "dark urine":           "dark_urine",
    "brown urine":          "dark_urine",
    "bloody stool":         "bloody_stool",
    "blood in stool":       "bloody_stool",
    "burning urination":    "burning_micturition",
    "burning while urinating": "burning_micturition",
    "painful urination":    "burning_micturition",

    # ── General ───────────────────────────────────────────────────────────────
    "tired":                "fatigue",
    "tiredness":            "fatigue",
    "exhausted":            "fatigue",
    "exhaustion":           "fatigue",
    "fatigue":              "fatigue",
    "weakness":             "fatigue",
    "weak":                 "fatigue",
    "no energy":            "fatigue",
    "lethargy":             "lethargy",
    "lethargic":            "lethargy",
    "dizziness":            "dizziness",
    "dizzy":                "dizziness",
    "lightheaded":          "dizziness",
    "light headed":         "dizziness",
    "spinning":             "spinning_movements",
    "vertigo":              "spinning_movements",
    "room spinning":        "spinning_movements",
    "sweating":             "sweating",
    "excessive sweating":   "sweating",
    "night sweats":         "sweating",
    "sweaty":               "sweating",
    "shivering":            "shivering",
    "chills":               "chills",
    "cold chills":          "chills",
    "feeling cold":         "chills",
    "dehydrated":           "dehydration",
    "dehydration":          "dehydration",
    "weight loss":          "weight_loss",
    "losing weight":        "weight_loss",
    "weight gain":          "weight_gain",
    "gaining weight":       "weight_gain",
    "swelling":             "swelled_lymph_nodes",
    "swollen":              "swelled_lymph_nodes",
    "lymph nodes":          "swelled_lymph_nodes",
    "swollen glands":       "swelled_lymph_nodes",
    "anxiety":              "anxiety",
    "anxious":              "anxiety",
    "depression":           "depression",
    "depressed":            "depression",
    "mood swings":          "mood_swings",
    "irritability":         "irritability",
    "irritable":            "irritability",
    "restlessness":         "restlessness",
    "restless":             "restlessness",
    "palpitations":         "palpitations",
    "heart racing":         "fast_heart_rate",
    "fast heartbeat":       "fast_heart_rate",
    "rapid heartbeat":      "fast_heart_rate",
    "fast pulse":           "fast_heart_rate",
    "blurred vision":       "blurred_and_distorted_vision",
    "vision problems":      "blurred_and_distorted_vision",
    "vision blurred":       "blurred_and_distorted_vision",
    "stiff neck":           "stiff_neck",
    "neck stiffness":       "stiff_neck",
    "frequent urination":   "polyuria",
    "urinating frequently": "polyuria",
    "excessive thirst":     "irregular_sugar_level",
    "very thirsty":         "irregular_sugar_level",
    "increased hunger":     "excessive_hunger",
    "always hungry":        "excessive_hunger",
    "malaise":              "malaise",
    "unwell":               "malaise",
    "feeling unwell":       "malaise",
    "not well":             "malaise",
    "cold hands":           "cold_hands_and_feets",
    "cold feet":            "cold_hands_and_feets",
    "cold hands and feet":  "cold_hands_and_feets",
    "sunken eyes":          "sunken_eyes",
    "puffy face":           "puffy_face_and_eyes",
    "swollen face":         "puffy_face_and_eyes",
    "loss of smell":        "loss_of_smell",
    "cant smell":           "loss_of_smell",
    "muscle wasting":       "muscle_wasting",
    "muscle weakness":      "muscle_weakness",
}
